services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/build
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=cesta
      - MYSQL_USER=cesta
      - MYSQL_PASSWORD=senhasegura123
      - MYSQL_ROOT_PASSWORD=senhasegura123
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senhasegura123
