services:
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=cesta
      - MYSQL_USER=cesta
      - MYSQL_PASSWORD=senhasegura123
      - MYSQL_ROOT_PASSWORD=senhasegura123
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senhasegura123